USE fit_alunos
GO 
/*======================================================================================
			TOTAL DE ALUNOS POR DISCIPLINAOFERTADA - COORDENADOR
=======================================================================================*/
SELECT DISC.NOME AS NOME_DISCIPLINA_OFERTADA, COUNT (SM.ID_ALUNO) AS TOTAL 
FROM DISCIPLINA_OFERTADAIMP DOF
LEFT JOIN DISCIPLINAIMP DISC
ON DISC.ID_DISCIPLINA = DOF.IDDISCOF
LEFT JOIN  SOLICITACAO_MATRICULAIMP SM
ON DOF.IDDISCOF = SM.ID_DISCIPLINAOFERT
GROUP BY DISC.NOME

/*======================================================================================
			TOTAL DE ALUNOS POR DISCIPLINAOFERTADA - COORDENADOR
=======================================================================================*/

SELECT ENT.ID_ALUNO, ATV.ID_DISCOF, ATV.ID_ATIVIDADE, ATV.ID_ATIVID_VINC, 

/*	CASE WHEN ATV.ID_ATIVID = 1 AND ATV.ID_ATIVID_VINC = 1 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_1,
	CASE WHEN ATV.ID_ATIVID = 2 AND ATV.ID_ATIVID_VINC = 2 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_2,
	CASE WHEN ATV.ID_ATIVID = 3 AND ATV.ID_ATIVID_VINC = 3 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_3,
	CASE WHEN ATV.ID_ATIVID = 4 AND ATV.ID_ATIVID_VINC = 4 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_4,
	CASE WHEN ATV.ID_ATIVID = 5 AND ATV.ID_ATIVID_VINC = 5 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_5,
	CASE WHEN ATV.ID_ATIVID = 6 AND ATV.ID_ATIVID_VINC = 6 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_6,
	CASE WHEN ATV.ID_ATIVID = 7 AND ATV.ID_ATIVID_VINC = 7 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_7,
	CASE WHEN ATV.ID_ATIVID = 8 AND ATV.ID_ATIVID_VINC = 8 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_8,
	CASE WHEN ATV.ID_ATIVID = 9 AND ATV.ID_ATIVID_VINC = 9 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_9,
	CASE WHEN ATV.ID_ATIVID = 10 AND ATV.ID_ATIVID_VINC = 10 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_10,*/

	CASE WHEN ATV.ID_ATIVIDADE = 1 AND ATV.ID_ATIVID_VINC = 1 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_1,
	CASE WHEN ATV.ID_ATIVIDADE = 2 AND ATV.ID_ATIVID_VINC = 2 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_2,
	CASE WHEN ATV.ID_ATIVIDADE = 3 AND ATV.ID_ATIVID_VINC = 3 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_3,
	CASE WHEN ATV.ID_ATIVIDADE = 4 AND ATV.ID_ATIVID_VINC = 4 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_4,
	CASE WHEN ATV.ID_ATIVIDADE = 5 AND ATV.ID_ATIVID_VINC = 5 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_5,
	CASE WHEN ATV.ID_ATIVIDADE = 6 AND ATV.ID_ATIVID_VINC = 6 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_6,
	CASE WHEN ATV.ID_ATIVIDADE = 7 AND ATV.ID_ATIVID_VINC = 7 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_7,
	CASE WHEN ATV.ID_ATIVIDADE = 8 AND ATV.ID_ATIVID_VINC = 8 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_8,
	CASE WHEN ATV.ID_ATIVIDADE = 9 AND ATV.ID_ATIVID_VINC = 9 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_9,
	CASE WHEN ATV.ID_ATIVIDADE = 10 AND ATV.ID_ATIVID_VINC = 10 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_10

FROM ENTREGAIMP ENT
LEFT JOIN ATIVIDADE_VINCULADAIMP ATV
ON ATV.ID_ATIVID_VINC = ENT.ID_ATIVID_VINC

/*======================================================================================
			TOTAL DE ALUNOS POR DISCIPLINAOFERTADA - COORDENADOR
=======================================================================================*/

SELECT ENT.ID_ALUNO, ATV.ID_ATIVIDADE, ATV.ID_ATIVID_VINC,

/*	CASE WHEN ATV.ID_ATIVID = 1 AND ATV.ID_ATIVID_VINC = 1 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_1,
	CASE WHEN ATV.ID_ATIVID = 2 AND ATV.ID_ATIVID_VINC = 2 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_2,
	CASE WHEN ATV.ID_ATIVID = 3 AND ATV.ID_ATIVID_VINC = 3 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_3,
	CASE WHEN ATV.ID_ATIVID = 4 AND ATV.ID_ATIVID_VINC = 4 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_4,
	CASE WHEN ATV.ID_ATIVID = 5 AND ATV.ID_ATIVID_VINC = 5 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_5,
	CASE WHEN ATV.ID_ATIVID = 6 AND ATV.ID_ATIVID_VINC = 6 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_6,
	CASE WHEN ATV.ID_ATIVID = 7 AND ATV.ID_ATIVID_VINC = 7 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_7,
	CASE WHEN ATV.ID_ATIVID = 8 AND ATV.ID_ATIVID_VINC = 8 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_8,
	CASE WHEN ATV.ID_ATIVID = 9 AND ATV.ID_ATIVID_VINC = 9 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_9,
	CASE WHEN ATV.ID_ATIVID = 10 AND ATV.ID_ATIVID_VINC = 10 AND ENT.DTENTREGA > ATV.DTFIMRESPOSTAS THEN '0' ELSE ENT.NOTA END AS NOTA_10,*/

	CASE WHEN ATV.ID_ATIVIDADE = 1 AND ATV.ID_ATIVID_VINC = 1 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_1,
	CASE WHEN ATV.ID_ATIVIDADE = 2 AND ATV.ID_ATIVID_VINC = 2 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_2,
	CASE WHEN ATV.ID_ATIVIDADE = 3 AND ATV.ID_ATIVID_VINC = 3 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_3,
	CASE WHEN ATV.ID_ATIVIDADE = 4 AND ATV.ID_ATIVID_VINC = 4 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_4,
	CASE WHEN ATV.ID_ATIVIDADE = 5 AND ATV.ID_ATIVID_VINC = 5 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_5,
	CASE WHEN ATV.ID_ATIVIDADE = 6 AND ATV.ID_ATIVID_VINC = 6 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_6,
	CASE WHEN ATV.ID_ATIVIDADE = 7 AND ATV.ID_ATIVID_VINC = 7 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_7,
	CASE WHEN ATV.ID_ATIVIDADE = 8 AND ATV.ID_ATIVID_VINC = 8 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_8,
	CASE WHEN ATV.ID_ATIVIDADE = 9 AND ATV.ID_ATIVID_VINC = 9 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_9,
	CASE WHEN ATV.ID_ATIVIDADE = 10 AND ATV.ID_ATIVID_VINC = 10 AND ENT.[STATUS] NOT IN ('ENTREGUE') THEN '0' ELSE ENT.NOTA END AS NOTA_10

FROM ENTREGAIMP ENT
LEFT JOIN ATIVIDADE_VINCULADAIMP ATV
ON ATV.ID_ATIVID_VINC = ENT.ID_ATIVID_VINC


SELECT ID_ALUNO, ID_ATIVID_VINC, AVG(NOTA) AS MEDIA FROM ENTREGAIMP
GROUP BY ID_ALUNO, ID_ATIVID_VINC